### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by mcandre** [jonay2000/label#32]
Hi,

label no longer compiles with Rust 1.91.0+.

```
error[E0432]: unresolved import `syn::export`
  --> /Users/andrew/.asdf/installs/rust/1.91.1/registry/src/index.crates.io-1949cf8c6b5b557f/label-macros-0.6.0/src/lib.rs:14:10
   |
14 | use syn::export::ToTokens;
   |          ^^^^^^ could not find `export` in `syn`

error[E0433]: failed to resolve: could not find `export` in `syn`
  --> /Users/andrew/.asdf/installs/rust/1.91.1/registry/src/index.crates.io-1949cf8c6b5b557f/label-macros-0.6.0/src/lib.rs:78:43
   |
78 |     fn to_tokens(&self, tokens: &mut syn::export::TokenStream2) {
   |                                           ^^^^^^ could not find `export` in `syn`

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /Users/andrew/.asdf/installs/rust/1.91.1/registry/src/index.crates.io-1949cf8c6b5b557f/label-macros-0.6.0/src/lib.rs:2:1
  |
2 | #![feature(proc_macro_span)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Please update this crate to work with newer Rust versions.

As well, ensure that the crate compiles with the newest Rust edition.
